schema_version: 1

context:
  name: ontolutils
  version: 0.21.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ontolutils-${{ version }}.tar.gz
  sha256: d6cb6eafc4190bb8b431b7a17b7e82302ae183f40d60a1c862b9056eaac946a4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=78.1.1
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - rdflib >=7.0.0
    - pydantic >=2.8.2
    - python-dateutil >=2.9.0
    - requests >=2.32.3
    - appdirs >=1.4.4
    - pyyaml >=6.0
tests:
  - python:
      imports:
        - ontolutils
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Utility library for the work with ontologies.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/matthiasprobst/ontology-utils

extra:
  recipe-maintainers:
    - jan-janssen
